from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QGridLayout, QHBoxLayout,
    QLabel, QLineEdit, QPushButton, QRadioButton,
    QScrollArea, QSizePolicy, QSpacerItem, QWidget)
from ImageBox import ImageWidget
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(650, 500)
        self.gridLayout = QGridLayout(Dialog)
        self.gridLayout.setObjectName(u"gridLayout")
        self.label_6 = QLabel(Dialog)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.pushButton_2 = QPushButton(Dialog)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 9, 2, 1, 1)
        self.pushButton_3 = QPushButton(Dialog)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 7, 4, 1, 1)
        self.lineEdit_3 = QLineEdit(Dialog)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 3, 1, 2)
        self.lineEdit_2 = QLineEdit(Dialog)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 6, 2, 1, 3)
        self.label_5 = QLabel(Dialog)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_5, 7, 2, 1, 2)
        self.lineEdit = QLineEdit(Dialog)
        self.lineEdit.setObjectName(u"lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 4, 2, 1, 3)
        self.label_3 = QLabel(Dialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_3, 5, 2, 1, 1)
        self.radioButton = QRadioButton(Dialog)
        self.radioButton.setObjectName(u"radioButton")
        self.gridLayout.addWidget(self.radioButton, 0, 3, 1, 1)
        self.pushButton = QPushButton(Dialog)
        self.pushButton.setObjectName(u"pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.horizontalSpacer_3 = QSpacerItem(272, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.gridLayout.addItem(self.horizontalSpacer_3, 8, 2, 1, 3)
        self.label_2 = QLabel(Dialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_2, 3, 2, 1, 1)
        self.radioButton_2 = QRadioButton(Dialog)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 0, 4, 1, 1)
        self.widget = QWidget(Dialog)
        self.widget.setObjectName(u"widget")
        self.horizontalLayout = QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.radioButton_3 = QRadioButton(self.widget)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QRadioButton(self.widget)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.horizontalLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QRadioButton(self.widget)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.horizontalLayout.addWidget(self.radioButton_5)
        self.gridLayout.addWidget(self.widget, 1, 2, 1, 3)
        self.widget_2 = QWidget(Dialog)
        self.widget_2.setObjectName(u"widget_2")
        self.horizontalLayout_2 = QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.radioButton_6 = QRadioButton(self.widget_2)
        self.radioButton_6.setObjectName(u"radioButton_6")
        self.horizontalLayout_2.addWidget(self.radioButton_6)
        self.radioButton_7 = QRadioButton(self.widget_2)
        self.radioButton_7.setObjectName(u"radioButton_7")
        self.horizontalLayout_2.addWidget(self.radioButton_7)
        self.gridLayout.addWidget(self.widget_2, 3, 3, 1, 2)
        self.scrollArea = QScrollArea(Dialog)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 349, 480))
        self.gridLayout_2 = QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.widget_3 = ImageWidget()
        self.widget_3.setObjectName(u"widget_3")
        self.gridLayout_2.addWidget(self.widget_3, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 10, 2)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout.setColumnStretch(4, 1)
        self.retranslateUi(Dialog)
        QMetaObject.connectSlotsByName(Dialog)
    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"\u56fe\u7247\u8bc6\u522b", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"\u56fe\u7247\u5730\u5740\uff1a", None))
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"\u5f00\u59cb\u8bc6\u522b", None))
        self.pushButton_3.setText(QCoreApplication.translate("Dialog", u"\u70b9\u51fb\u67e5\u8be2", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"\u5269\u4f59\u514d\u8d39\u7ffb\u8bd1\u6b21\u6570\uff1a", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"\u5bc6\u94a5", None))
        self.radioButton.setText(QCoreApplication.translate("Dialog", u"\u672c\u5730\u8bc6\u522b", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"\u6253\u5f00\u56fe\u7247", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"\u767e\u5ea6API\u63a5\u53e3\uff1a", None))
        self.radioButton_2.setText(QCoreApplication.translate("Dialog", u"\u8054\u7f51\u8bc6\u522b", None))
        self.radioButton_3.setText(QCoreApplication.translate("Dialog", u"\u82f1\u6587\u8bc6\u522b", None))
        self.radioButton_4.setText(QCoreApplication.translate("Dialog", u"\u4e2d\u6587\u8bc6\u522b", None))
        self.radioButton_5.setText(QCoreApplication.translate("Dialog", u"\u901a\u7528\u8bc6\u522b", None))
        self.radioButton_6.setText(QCoreApplication.translate("Dialog", u"\u6807\u51c6\u8bc6\u522b", None))
        self.radioButton_7.setText(QCoreApplication.translate("Dialog", u"\u7cbe\u786e\u8bc6\u522b", None))