from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGridLayout,
    QGroupBox, QHBoxLayout, QHeaderView, QLabel,
    QLineEdit, QListWidget, QListWidgetItem, QMainWindow,
    QMenuBar, QProgressBar, QPushButton, QSizePolicy,
    QSpacerItem, QSpinBox, QStatusBar, QTabWidget,
    QTextEdit, QTreeWidget, QTreeWidgetItem, QVBoxLayout,
    QWidget)
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1080, 720)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setTabPosition(QTabWidget.West)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.gridLayout_2 = QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setAlignment(Qt.AlignCenter)
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.pushButton_6 = QPushButton(self.tab)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 0, 4, 1, 1)
        self.pushButton_5 = QPushButton(self.tab)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 0, 3, 1, 1)
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.gridLayout_2.addWidget(self.label_2, 5, 7, 1, 1)
        self.widget_2 = QWidget(self.tab)
        self.widget_2.setObjectName(u"widget_2")
        self.horizontalLayout_2 = QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.pushButton_2 = QPushButton(self.widget_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QPushButton(self.widget_2)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.gridLayout_2.addWidget(self.widget_2, 3, 1, 1, 1)
        self.horizontalSpacer = QSpacerItem(418, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.gridLayout_2.addItem(self.horizontalSpacer, 2, 0, 1, 2)
        self.pushButton_4 = QPushButton(self.tab)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 3, 2, 1, 1)
        self.checkBox = QCheckBox(self.tab)
        self.checkBox.setObjectName(u"checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 2, 2, 1, 1)
        self.widget = QWidget(self.tab)
        self.widget.setObjectName(u"widget")
        self.horizontalLayout = QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.lineEdit = QLineEdit(self.widget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setInputMethodHints(Qt.ImhPreferLatin)
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QPushButton(self.widget)
        self.pushButton.setObjectName(u"pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 2, 3)
        self.lineEdit_2 = QLineEdit(self.tab)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 5, 1, 3)
        self.pushButton_7 = QPushButton(self.tab)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 5, 3, 1, 1)
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.gridLayout_2.addWidget(self.label_3, 5, 6, 1, 1)
        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.gridLayout_2.addItem(self.horizontalSpacer_2, 5, 0, 1, 2)
        self.textEdit = QTextEdit(self.tab)
        self.textEdit.setObjectName(u"textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 4, 0, 1, 3)
        self.horizontalSpacer_3 = QSpacerItem(190, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.gridLayout_2.addItem(self.horizontalSpacer_3, 5, 4, 1, 2)
        self.treeWidget_2 = QTreeWidget(self.tab)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"1");
        self.treeWidget_2.setHeaderItem(__qtreewidgetitem)
        self.treeWidget_2.setObjectName(u"treeWidget_2")
        self.gridLayout_2.addWidget(self.treeWidget_2, 1, 3, 4, 5)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setColumnStretch(3, 1)
        self.gridLayout_2.setColumnStretch(4, 1)
        self.gridLayout_2.setColumnStretch(6, 1)
        self.gridLayout_2.setColumnStretch(7, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.gridLayout_4 = QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.progressBar = QProgressBar(self.tab_2)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setValue(24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(Qt.Horizontal)
        self.progressBar.setTextDirection(QProgressBar.TopToBottom)
        self.gridLayout_4.addWidget(self.progressBar, 0, 0, 1, 3)
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.gridLayout_4.addWidget(self.label_6, 0, 3, 1, 1)
        self.treeWidget = QTreeWidget(self.tab_2)
        __qtreewidgetitem1 = QTreeWidgetItem()
        __qtreewidgetitem1.setText(0, u"1");
        self.treeWidget.setHeaderItem(__qtreewidgetitem1)
        self.treeWidget.setObjectName(u"treeWidget")
        self.gridLayout_4.addWidget(self.treeWidget, 0, 4, 5, 1)
        self.label_4 = QLabel(self.tab_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setAlignment(Qt.AlignCenter)
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 2, 1)
        self.label_5 = QLabel(self.tab_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setAlignment(Qt.AlignCenter)
        self.gridLayout_4.addWidget(self.label_5, 1, 1, 2, 1)
        self.pushButton_8 = QPushButton(self.tab_2)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.gridLayout_4.addWidget(self.pushButton_8, 1, 2, 1, 1)
        self.pushButton_12 = QPushButton(self.tab_2)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.gridLayout_4.addWidget(self.pushButton_12, 1, 3, 2, 1)
        self.pushButton_9 = QPushButton(self.tab_2)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.gridLayout_4.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.pushButton_10 = QPushButton(self.tab_2)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.gridLayout_4.addWidget(self.pushButton_10, 3, 0, 1, 1)
        self.pushButton_11 = QPushButton(self.tab_2)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.gridLayout_4.addWidget(self.pushButton_11, 3, 1, 1, 1)
        self.groupBox = QGroupBox(self.tab_2)
        self.groupBox.setObjectName(u"groupBox")
        self.gridLayout_3 = QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.pushButton_13 = QPushButton(self.groupBox)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.gridLayout_3.addWidget(self.pushButton_13, 0, 0, 1, 1)
        self.lineEdit_3 = QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.treeWidget_3 = QTreeWidget(self.groupBox)
        __qtreewidgetitem2 = QTreeWidgetItem()
        __qtreewidgetitem2.setText(0, u"1");
        self.treeWidget_3.setHeaderItem(__qtreewidgetitem2)
        self.treeWidget_3.setObjectName(u"treeWidget_3")
        self.gridLayout_3.addWidget(self.treeWidget_3, 1, 0, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox, 3, 2, 2, 2)
        self.textEdit_2 = QTextEdit(self.tab_2)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.gridLayout_4.addWidget(self.textEdit_2, 4, 0, 1, 2)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.gridLayout_7 = QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.label_11 = QLabel(self.tab_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setAlignment(Qt.AlignCenter)
        self.gridLayout_7.addWidget(self.label_11, 0, 8, 1, 1)
        self.groupBox_2 = QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.gridLayout_5 = QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.textEdit_3 = QTextEdit(self.groupBox_2)
        self.textEdit_3.setObjectName(u"textEdit_3")
        self.gridLayout_5.addWidget(self.textEdit_3, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 2, 0, 1, 6)
        self.comboBox_2 = QComboBox(self.tab_3)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.gridLayout_7.addWidget(self.comboBox_2, 1, 9, 1, 1)
        self.pushButton_18 = QPushButton(self.tab_3)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.gridLayout_7.addWidget(self.pushButton_18, 1, 10, 1, 2)
        self.label_9 = QLabel(self.tab_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setAlignment(Qt.AlignCenter)
        self.gridLayout_7.addWidget(self.label_9, 0, 4, 1, 1)
        self.label_10 = QLabel(self.tab_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setAlignment(Qt.AlignCenter)
        self.gridLayout_7.addWidget(self.label_10, 1, 4, 1, 1)
        self.lineEdit_5 = QLineEdit(self.tab_3)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.gridLayout_7.addWidget(self.lineEdit_5, 1, 5, 1, 2)
        self.lineEdit_4 = QLineEdit(self.tab_3)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.gridLayout_7.addWidget(self.lineEdit_4, 0, 5, 1, 2)
        self.groupBox_3 = QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.gridLayout_6 = QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.textEdit_4 = QTextEdit(self.groupBox_3)
        self.textEdit_4.setObjectName(u"textEdit_4")
        self.gridLayout_6.addWidget(self.textEdit_4, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 2, 6, 1, 6)
        self.pushButton_15 = QPushButton(self.tab_3)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.gridLayout_7.addWidget(self.pushButton_15, 1, 0, 1, 1)
        self.pushButton_14 = QPushButton(self.tab_3)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.gridLayout_7.addWidget(self.pushButton_14, 0, 0, 1, 1)
        self.comboBox = QComboBox(self.tab_3)
        self.comboBox.setObjectName(u"comboBox")
        self.gridLayout_7.addWidget(self.comboBox, 1, 8, 1, 1)
        self.label_8 = QLabel(self.tab_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.gridLayout_7.addWidget(self.label_8, 0, 10, 1, 1)
        self.verticalSpacer_2 = QSpacerItem(20, 51, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.gridLayout_7.addItem(self.verticalSpacer_2, 0, 3, 2, 1)
        self.verticalSpacer = QSpacerItem(20, 51, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.gridLayout_7.addItem(self.verticalSpacer, 0, 7, 2, 1)
        self.pushButton_16 = QPushButton(self.tab_3)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.gridLayout_7.addWidget(self.pushButton_16, 0, 1, 1, 1)
        self.pushButton_17 = QPushButton(self.tab_3)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.gridLayout_7.addWidget(self.pushButton_17, 1, 1, 1, 1)
        self.pushButton_19 = QPushButton(self.tab_3)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.gridLayout_7.addWidget(self.pushButton_19, 0, 11, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.gridLayout_16 = QGridLayout(self.tab_4)
        self.gridLayout_16.setObjectName(u"gridLayout_16")
        self.groupBox_6 = QGroupBox(self.tab_4)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.gridLayout_17 = QGridLayout(self.groupBox_6)
        self.gridLayout_17.setObjectName(u"gridLayout_17")
        self.groupBox_10 = QGroupBox(self.groupBox_6)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.gridLayout_13 = QGridLayout(self.groupBox_10)
        self.gridLayout_13.setObjectName(u"gridLayout_13")
        self.pushButton_32 = QPushButton(self.groupBox_10)
        self.pushButton_32.setObjectName(u"pushButton_32")
        self.gridLayout_13.addWidget(self.pushButton_32, 0, 0, 1, 1)
        self.pushButton_33 = QPushButton(self.groupBox_10)
        self.pushButton_33.setObjectName(u"pushButton_33")
        self.gridLayout_13.addWidget(self.pushButton_33, 0, 1, 1, 1)
        self.groupBox_11 = QGroupBox(self.groupBox_10)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.gridLayout_12 = QGridLayout(self.groupBox_11)
        self.gridLayout_12.setObjectName(u"gridLayout_12")
        self.listWidget = QListWidget(self.groupBox_11)
        self.listWidget.setObjectName(u"listWidget")
        self.gridLayout_12.addWidget(self.listWidget, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_11, 1, 0, 1, 2)
        self.gridLayout_17.addWidget(self.groupBox_10, 2, 3, 2, 1)
        self.label_7 = QLabel(self.groupBox_6)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setAlignment(Qt.AlignCenter)
        self.gridLayout_17.addWidget(self.label_7, 0, 0, 1, 2)
        self.groupBox_5 = QGroupBox(self.groupBox_6)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.gridLayout_9 = QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.label_12 = QLabel(self.groupBox_5)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setAlignment(Qt.AlignCenter)
        self.gridLayout_9.addWidget(self.label_12, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_5, 0, 3, 2, 1)
        self.groupBox_12 = QGroupBox(self.groupBox_6)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.verticalLayout_2 = QVBoxLayout(self.groupBox_12)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.groupBox_13 = QGroupBox(self.groupBox_12)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.gridLayout_14 = QGridLayout(self.groupBox_13)
        self.gridLayout_14.setObjectName(u"gridLayout_14")
        self.pushButton_34 = QPushButton(self.groupBox_13)
        self.pushButton_34.setObjectName(u"pushButton_34")
        self.gridLayout_14.addWidget(self.pushButton_34, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_13)
        self.groupBox_14 = QGroupBox(self.groupBox_12)
        self.groupBox_14.setObjectName(u"groupBox_14")
        self.gridLayout_15 = QGridLayout(self.groupBox_14)
        self.gridLayout_15.setObjectName(u"gridLayout_15")
        self.comboBox_3 = QComboBox(self.groupBox_14)
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.gridLayout_15.addWidget(self.comboBox_3, 0, 1, 1, 1)
        self.label_18 = QLabel(self.groupBox_14)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setAlignment(Qt.AlignCenter)
        self.gridLayout_15.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QLabel(self.groupBox_14)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setAlignment(Qt.AlignCenter)
        self.gridLayout_15.addWidget(self.label_19, 1, 0, 1, 1)
        self.comboBox_4 = QComboBox(self.groupBox_14)
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.gridLayout_15.addWidget(self.comboBox_4, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_14)
        self.gridLayout_17.addWidget(self.groupBox_12, 0, 4, 4, 1)
        self.groupBox_4 = QGroupBox(self.groupBox_6)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.gridLayout_8 = QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.lineEdit_6 = QLineEdit(self.groupBox_4)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.gridLayout_8.addWidget(self.lineEdit_6, 0, 0, 1, 2)
        self.pushButton_23 = QPushButton(self.groupBox_4)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.gridLayout_8.addWidget(self.pushButton_23, 1, 2, 1, 1)
        self.pushButton_20 = QPushButton(self.groupBox_4)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.gridLayout_8.addWidget(self.pushButton_20, 0, 2, 1, 1)
        self.pushButton_21 = QPushButton(self.groupBox_4)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.gridLayout_8.addWidget(self.pushButton_21, 1, 0, 1, 1)
        self.pushButton_22 = QPushButton(self.groupBox_4)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.gridLayout_8.addWidget(self.pushButton_22, 1, 1, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_4, 3, 0, 1, 3)
        self.groupBox_7 = QGroupBox(self.groupBox_6)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.verticalLayout = QVBoxLayout(self.groupBox_7)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.groupBox_8 = QGroupBox(self.groupBox_7)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.gridLayout_10 = QGridLayout(self.groupBox_8)
        self.gridLayout_10.setObjectName(u"gridLayout_10")
        self.pushButton_24 = QPushButton(self.groupBox_8)
        self.pushButton_24.setObjectName(u"pushButton_24")
        self.gridLayout_10.addWidget(self.pushButton_24, 0, 0, 1, 2)
        self.pushButton_25 = QPushButton(self.groupBox_8)
        self.pushButton_25.setObjectName(u"pushButton_25")
        self.gridLayout_10.addWidget(self.pushButton_25, 0, 2, 1, 2)
        self.label_13 = QLabel(self.groupBox_8)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setAlignment(Qt.AlignCenter)
        self.gridLayout_10.addWidget(self.label_13, 1, 0, 1, 1)
        self.lineEdit_7 = QLineEdit(self.groupBox_8)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.gridLayout_10.addWidget(self.lineEdit_7, 1, 1, 1, 2)
        self.pushButton_28 = QPushButton(self.groupBox_8)
        self.pushButton_28.setObjectName(u"pushButton_28")
        self.gridLayout_10.addWidget(self.pushButton_28, 1, 3, 1, 1)
        self.label_14 = QLabel(self.groupBox_8)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setAlignment(Qt.AlignCenter)
        self.gridLayout_10.addWidget(self.label_14, 2, 0, 1, 1)
        self.lineEdit_8 = QLineEdit(self.groupBox_8)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.gridLayout_10.addWidget(self.lineEdit_8, 2, 1, 1, 2)
        self.pushButton_29 = QPushButton(self.groupBox_8)
        self.pushButton_29.setObjectName(u"pushButton_29")
        self.gridLayout_10.addWidget(self.pushButton_29, 2, 3, 1, 1)
        self.gridLayout_10.setColumnStretch(0, 1)
        self.gridLayout_10.setColumnStretch(1, 1)
        self.gridLayout_10.setColumnStretch(2, 1)
        self.gridLayout_10.setColumnStretch(3, 1)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.groupBox_9 = QGroupBox(self.groupBox_7)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.gridLayout_11 = QGridLayout(self.groupBox_9)
        self.gridLayout_11.setObjectName(u"gridLayout_11")
        self.pushButton_26 = QPushButton(self.groupBox_9)
        self.pushButton_26.setObjectName(u"pushButton_26")
        self.gridLayout_11.addWidget(self.pushButton_26, 0, 0, 1, 2)
        self.label_16 = QLabel(self.groupBox_9)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setAlignment(Qt.AlignCenter)
        self.gridLayout_11.addWidget(self.label_16, 1, 0, 1, 1)
        self.lineEdit_9 = QLineEdit(self.groupBox_9)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.gridLayout_11.addWidget(self.lineEdit_9, 1, 1, 1, 2)
        self.pushButton_30 = QPushButton(self.groupBox_9)
        self.pushButton_30.setObjectName(u"pushButton_30")
        self.gridLayout_11.addWidget(self.pushButton_30, 1, 3, 1, 1)
        self.label_15 = QLabel(self.groupBox_9)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setAlignment(Qt.AlignCenter)
        self.gridLayout_11.addWidget(self.label_15, 2, 0, 1, 1)
        self.lineEdit_10 = QLineEdit(self.groupBox_9)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.gridLayout_11.addWidget(self.lineEdit_10, 2, 1, 1, 2)
        self.pushButton_31 = QPushButton(self.groupBox_9)
        self.pushButton_31.setObjectName(u"pushButton_31")
        self.gridLayout_11.addWidget(self.pushButton_31, 2, 3, 1, 1)
        self.pushButton_27 = QPushButton(self.groupBox_9)
        self.pushButton_27.setObjectName(u"pushButton_27")
        self.gridLayout_11.addWidget(self.pushButton_27, 0, 2, 1, 2)
        self.gridLayout_11.setColumnStretch(0, 1)
        self.gridLayout_11.setColumnStretch(1, 1)
        self.gridLayout_11.setColumnStretch(2, 1)
        self.gridLayout_11.setColumnStretch(3, 1)
        self.verticalLayout.addWidget(self.groupBox_9)
        self.gridLayout_17.addWidget(self.groupBox_7, 1, 0, 2, 3)
        self.spinBox = QSpinBox(self.groupBox_6)
        self.spinBox.setObjectName(u"spinBox")
        self.gridLayout_17.addWidget(self.spinBox, 0, 2, 1, 1)
        self.gridLayout_17.setColumnStretch(0, 1)
        self.gridLayout_17.setColumnStretch(1, 1)
        self.gridLayout_17.setColumnStretch(2, 1)
        self.gridLayout_17.setColumnStretch(3, 2)
        self.gridLayout_17.setColumnStretch(4, 2)
        self.gridLayout_16.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1080, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u6807", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u751f\u8bcd\u672c", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa\u751f\u8bcd\u672c", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u7f51\u7edc\u72b6\u6001", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u82f1", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\u7f8e", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"\u52a0\u5165\u751f\u8bcd\u672c", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"\u8054\u7f51\u67e5\u8be2", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u65f6\u95f4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u4e3b\u9875", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u5355\u8bcd", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u6807", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"\n"
"\u82f1\n"
"", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"\n"
"\u6682\u505c\n"
"", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"\n"
"\u7f8e\n"
"", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"\n"
"\u901a\u8fc7\n"
"", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"\n"
"\u4e0d\u8ba4\u8bc6\n"
"", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u9519\u8bcd\u672c", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6587\u4ef6\u8def\u5f84", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u5355\u8bcd\u6d4b\u9a8c", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u7ffb\u8bd1\u6a21\u5f0f\uff1a", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\u539f\u6587", None))
        self.pushButton_18.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb\u7ffb\u8bd1", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u767e\u5ea6API\u63a5\u53e3ID\uff1a", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u5bc6\u94a5\uff1a", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"\u8bd1\u6587", None))
        self.textEdit_4.setMarkdown("")
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u7247\u8bc6\u522b", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"\u526a\u5207\u677f", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u5269\u4f59\u514d\u8d39\u7ffb\u8bd1\u5b57\u6570\uff1a", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6\u5bfc\u5165", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"\u8bed\u97f3\u5f55\u5165", None))
        self.pushButton_19.setText(QCoreApplication.translate("MainWindow", u"\u70b9\u51fb\u67e5\u8be2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u6587\u672c\u7ffb\u8bd1", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"\u57fa\u7840\u8bbe\u7f6e", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"\u901a\u7528", None))
        self.pushButton_32.setText(QCoreApplication.translate("MainWindow", u"\u6e05\u9664\u7f13\u5b58", None))
        self.pushButton_33.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6587\u4ef6\u8def\u5f84", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"\u5355\u8bcd\u672c\u4f7f\u7528\u5386\u53f2", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u5012\u8ba1\u65f6", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"\u672c\u673a\u60c5\u51b5", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u672c\u673a\u60c5\u51b5", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"\u5176\u4ed6", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"\u672c\u5730OCR\u8bad\u7ec3", None))
        self.pushButton_34.setText(QCoreApplication.translate("MainWindow", u"\u70b9\u51fb\u67e5\u770b\u8bad\u7ec3\u6307\u5357", None))
        self.groupBox_14.setTitle(QCoreApplication.translate("MainWindow", u"\u8f6f\u4ef6\u4e3b\u9898", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\u4e3b\u9898", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\u5355\u8bcd\u6d4b\u9a8c\u91ca\u4e49\u7b56\u7565", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"\u5355\u8bcd\u8bfb\u97f3\u8bbe\u7f6e", None))
        self.pushButton_23.setText(QCoreApplication.translate("MainWindow", u"\u7535\u8111\u5408\u6210", None))
        self.pushButton_20.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2", None))
        self.pushButton_21.setText(QCoreApplication.translate("MainWindow", u"\u82f1\u97f3\u4e0b\u8f7d", None))
        self.pushButton_22.setText(QCoreApplication.translate("MainWindow", u"\u7f8e\u97f3\u4e0b\u8f7d", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"\u767e\u5ea6API\u7ba1\u7406", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"\u767e\u5ea6\u7ffb\u8bd1", None))
        self.pushButton_24.setText(QCoreApplication.translate("MainWindow", u"\u8d26\u53f7\u7533\u8bf7", None))
        self.pushButton_25.setText(QCoreApplication.translate("MainWindow", u"\u7533\u8bf7\u6307\u5357", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"API ID", None))
        self.pushButton_28.setText("")
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u5bc6\u94a5", None))
        self.pushButton_29.setText("")
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u5b57\u8bc6\u522b", None))
        self.pushButton_26.setText(QCoreApplication.translate("MainWindow", u"\u8d26\u53f7\u7533\u8bf7", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"API ID", None))
        self.pushButton_30.setText("")
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\u5bc6\u94a5", None))
        self.pushButton_31.setText("")
        self.pushButton_27.setText(QCoreApplication.translate("MainWindow", u"\u7533\u8bf7\u6307\u5357", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"\u4e2a\u6027\u5316", None))